---
title: "stricterCriteria"
author: "Karen Solem Knutsen"
date: "20 7 2021"
output: html_document
---

```{r Set file name, include=FALSE}
old_file = "" # File to load data from
new_file = ""   # File to save data to
```


Define COLREGS
```{r COLREGS, include=FALSE} 
# Defining COLREG situations
OP      = -3.0    # Obstacle passed
OTGW    = -2.0    # Overtaking situation - own ship is give way vessel
CRGW    = -1.0    # Crossing situation - own ship is give way vessel
NAR     = 0.0     # No applicable rules
CRSO    = 1.0     # Crossing situation - own ship is stand on vessel
OTSO    = 2.0     # Overtaking situation - own ship is stand on vessel
HO      = 3.0     # Head on situation
STAT    = 4.0     # Static obstacle
``` 


```{r Load csv, include=FALSE} 
library(tidyverse)

# Load data
df <- read.csv(old_file, sep=";") 

# Deletes duplicate rows
df <- unique(df)

# Make sure columns has appropriate data type 
df$post_man_dist_own <- as.numeric(df$post_man_dist_own)
df$pre_man_dist_own <- as.numeric(df$pre_man_dist_own)
df$delta_course_own <- as.numeric(df$delta_course_own)
df$own_length <- as.numeric(df$own_length)
df$obst_length <- as.numeric(df$obst_length)
df$own_width <- as.numeric(df$own_width)
df$obst_width <- as.numeric(df$obst_width)
df$own_speed <- as.numeric(df$own_speed)
df$obst_speed <- as.numeric(df$obst_speed)
df$r_maneuver_own <- as.numeric(df$r_maneuver_own)
df$pre_man_dist_own <- as.numeric(df$pre_man_dist_own)
df$post_man_dist_own <- as.numeric(df$post_man_dist_own)
df$delta_speed_own <- as.numeric(df$delta_speed_own)
df$delta_speed_obst <- as.numeric(df$delta_speed_obst)
df$delta_course_obst <- as.numeric(df$delta_course_obst)
df$alpha_start <- as.numeric(df$alpha_start)
df$beta_start <- as.numeric(df$beta_start)
df$r_cpa <- as.numeric(df$r_cpa)
df$alpha_cpa <- as.numeric(df$alpha_cpa)
df$beta_cpa <- as.numeric(df$beta_cpa)
df$lon_maneuver <- as.numeric(df$lon_maneuver)
df$lat_maneuver <- as.numeric(df$lat_maneuver)
#df$dist_land <- as.numeric(df$dist_land)
df$own_nav_status <- as.numeric(df$own_nav_status)
df$obst_nav_status <- as.numeric(df$obst_nav_status)
df$COLREG <- as.numeric(df$COLREG)

# Replace missing values with -99
df$own_nav_status %>% replace_na(-99) 
df$obst_nav_status %>% replace_na(-99)


#df <- subset(df, img_class == "True")
```

```{r Col and ev, include=FALSE}
r_col         <- 0  # Minimum range for no collision at CPA
evasive_HO    <- 0  # Minimum change in distance between vessels to define a maneuver as evasive for HO. 
evasive_OTGW  <- 0  # Minimum change in distance between vessels to define a maneuver as evasive for OTGW.
evasive_OTSO  <- 0  # Minimum change in distance between vessels to define a maneuver as evasive for OTSO.
evasive_CRGW  <- 0  # Minimum change in distance between vessels to define a maneuver as evasive for CRGW.
evasive_CRSO  <- 0  # Minimum change in distance between vessels to define a maneuver as evasive for CRSO.

min_speed_HO    <- 0.0  # Minimum speed of own ship for HO
min_speed_CRGW  <- 0.0  # Minimum speed of own ship for CRGW
min_speed_OTGW  <- 0.0  # Minimum speed of own ship for OTGW
min_speed_OTSO  <- 0.0  # Minimum speed of own ship for OTSO
min_speed_CRSO  <- 0.0  # Minimum speed of own ship for CRSO

# Evasive maneuver
df$evasive_man <- as.logical((df$COLREG == HO & (as.logical((as.numeric(df$post_man_dist_own) - as.numeric(df$pre_man_dist_own)) > evasive_HO))) |
                            (df$COLREG == CRGW & (as.logical((as.numeric(df$post_man_dist_own) - as.numeric(df$pre_man_dist_own)) > evasive_CRGW))) |
                            (df$COLREG == OTGW & (as.logical((as.numeric(df$post_man_dist_own) - as.numeric(df$pre_man_dist_own)) > evasive_OTGW))) |
                            (df$COLREG == OTSO & (as.logical((as.numeric(df$post_man_dist_own) - as.numeric(df$pre_man_dist_own)) > evasive_OTSO))) | 
                            (df$COLREG == CRSO & (as.logical((as.numeric(df$post_man_dist_own) - as.numeric(df$pre_man_dist_own)) > evasive_CRSO))))

# No collision
df$no_collision <- as.logical(df$r_cpa > r_col)

# Speed criteria
df$speed_crit <- as.logical((df$COLREG == HO & df$own_speed > min_speed_HO) |
                            (df$COLREG == CRGW & df$own_speed > min_speed_CRGW) |
                            (df$COLREG == OTGW & df$own_speed > min_speed_OTGW) |
                            (df$COLREG == OTSO & df$own_speed > min_speed_OTSO) | 
                            (df$COLREG == CRSO & df$own_speed > min_speed_CRSO))

```

```{r COLREG_strict, include=FALSE}
# Not all situations defined as a COLREG situation by AutoVerification.py are perfect. Based on analyze of the data some stricter criteria where found. 

# Evasive maneuver made by ship and the case did not end in a collision 
df$COLREG_strict <- as.logical(df$evasive_man & df$no_collision)

# 0 = under way using engine / -99 = no info available 
df$COLREG_strict <- as.logical(df$COLREG_strict & (df$own_nav_status == 0 | df$own_nav_status == -99))

# Only allowed to take starboard maneuver for HO and CRGW
df$COLREG_strict <- as.logical(df$COLREG_strict & (((df$COLREG == HO | df$COLREG == CRGW) & df$delta_course_own < 0) 
                                                   | df$COLREG == OTGW | df$COLREG == OTSO | df$COLREG == CRSO))

HO1 <- subset(df, COLREG == HO)
CRGW1 <- subset(df, COLREG == CRGW)
OTGW1 <- subset(df, COLREG == OTGW)

```

Define stricter criteria for alpha and beta for some COLREG situations
```{r Alpha and beta, include=FALSE}
# Based on observations. May need to be adjusted. 
a_cpa_HO_min <- 30  # Minimum allowed contact angle for HO at CPA
a_cpa_HO_max <- 150 # Maximum allowed contact angle for HO at CPA
b_cpa_HO_min <- 30  # Minimum allowed relative bearing for HO at CPA
b_cpa_HO_max <- 150 # Maximum allowed relative bearing for HO at CPA

# Based on observations. May need to be adjusted. 
#a_cpa_OTGW_max    <- 0    # Maximum contact angle for OTGW at CPA. 
a_cpa_OTGW_min_abs <- 50   # Minimum absolute contact angle for OTGW at CPA.
b_cpa_OTGW_min     <- 150  # Minimum relative bearing for OTGW at CPA.
b_cpa_OTGW_max     <- 230  # Maximum relative bearing for OTGW at CPA.

# Based on observations. May need to be adjusted.
a_cpa_CRGW_min  <- 50  # Minimum contact angle for CRGW at CPA. 
a_cpa_CRGW_max  <- 180 # Maximum contact angle for CRGW at CPA.
b_cpa_CRGW_min  <- 0   # Minimum relative bearing for CRGW at CPA.
b_cpa_CRGW_max  <- 100 # Maximum relative bearing for CRGW at CPA.
  
# Some limitations on alpha and beta at CPA for various situations

df$COLREG_strict <- as.logical( df$COLREG_strict == TRUE &
                                  
                                ((df$COLREG == HO & df$beta_cpa > b_cpa_HO_min & df$beta_cpa < b_cpa_HO_max &
                                                      df$alpha_cpa > a_cpa_HO_min & df$alpha_cpa < a_cpa_HO_max) |
                                 
                                  (df$COLREG == OTGW & (df$beta_cpa > b_cpa_OTGW_min | df$beta_cpa < b_cpa_OTGW_max) &
                                                          abs(df$alpha_cpa) > a_cpa_OTGW_min_abs) |
                                   
                                   (df$COLREG == CRGW & df$beta_cpa > b_cpa_CRGW_min & df$beta_cpa < b_cpa_CRGW_max &
                                                           df$alpha_cpa > a_cpa_CRGW_min & df$alpha_cpa < a_cpa_CRGW_max) |
                                   df$COLREG == OTSO |
                                   
                                   df$COLREG == CRSO)
  
)


```

```{r Save to new csv, include=FALSE}

# Save data to new csv-file
write.csv2(df, new_file)
```